'
' FALSA Model Problem
' 
' Copyright 2024 Carnegie Mellon University.
' 
' NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE ENGINEERING
' INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS. CARNEGIE MELLON
' UNIVERSITY MAKES NO WARRANTIES OF ANY KIND, EITHER EXPRESSED OR IMPLIED, AS
' TO ANY MATTER INCLUDING, BUT NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE
' OR MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE OF THE
' MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE ANY WARRANTY OF ANY KIND
' WITH RESPECT TO FREEDOM FROM PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
' 
' Licensed under a MIT (SEI)-style license, please see license.txt or contact
' permission@sei.cmu.edu for full terms.
' 
' [DISTRIBUTION STATEMENT A] This material has been approved for public
' release and unlimited distribution.  Please see Copyright notice for non-US
' Government use and distribution.
' 
' This Software includes and/or makes use of Third-Party Software each subject
' to its own license.
' 
' DM24-0251
'
@startuml

frame Laptop {
frame Application as Frm1{
      node GCS as Node1
      node "Mission Manager" as Node2
      node Guidance as Node3
      node Payload as Node4
      node "Assurance Broker" as Node5
}

frame "Flight Control & Simulation" as Frm2 {
   node PX4 as Node6
   node JMavSim as Node7
}
}
Node1 <-> Node2 : GRPC
Node2 <-> Node3 : GRPC
Node2 <--> Node4 : GRPC
Node2 <--> Node5 : GRPC
Node3 <--> Frm2 : Mavlink
Node6 <--> Node7 : Sockets
@enduml
